# Default values for podmortem

replicaCount: 1

image:
  repository: devopsart1/podmortem
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Namespace to watch (empty = all namespaces)
watchNamespace: ""

# Enable verbose/debug logging
verbose: true

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
  # existingClaim: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podLabels: {}
